Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,4 +19,6 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
-            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'rm -rf /home/valerachornuy/htdocs && mkdir -p /home/valerachornuy/htdocs && git clone https://github.com/ValeriyChornuy/lab-2'
+            echo "Connecting to server..."
+            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'rm -rf /home/valerachornuy/htdocs && mkdir -p /home/valerachornuy/htdocs && git clone https://github.com/ValeriyChornuy/lab-2' || (echo "Failed to clone repository"; exit 1)
+            echo "Repository cloned successfully"
